classdef (Abstract) RetCell < nih.squirrellab.shared.sources.Cell
    
    methods
        
        function obj = RetCell()
            import symphonyui.core.*;
            
            obj.addProperty('type', '', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'', 'photoreceptor', 'horizontal', 'bipolar', 'amacrine', 'RGC', 'other', 'unknown'}, ...
                    { ...
                        {}, ...
                        {'S-cone', 'M-cone', 'L-cone', 'UV-cone', 'cone', 'rod'}, ...
                        {'H1', 'H2','H3','H4'}, ...
                        {'rbc', 'cbc', 'ONcbc', 'OFFcbc'}, ...
                        {'AII', 'A17', 'SAC', 'AC5170', 'vGlut3'}, ...
                        {'ipRGC','ON-alpha', 'ON-transient', 'OFF-transient', 'OFF-sustained', 'ON/OFF DS', 'ON DS', 'W3/local edge detector'}, ...
                        {}, ...
                        {}, ...
                    })), ...
                'description', 'The confirmed type of the recorded cell', ...
                'isPreferred', true);   
    end
    
    end
end
