classdef (Abstract) ImagingGroup < symphonyui.core.persistent.descriptions.EpochGroupDescription
    
    methods
        
        function obj = ImagingGroup()
            import symphonyui.core.*;
            
            obj.addProperty('externalSolutionAdditions', {}, ...
                'type', PropertyType('cellstr', 'row', {...
                'Tricaine',...
                'SR101 (1 uM)',...
                'SR101 (500 nM)',...
                'ZD7288 (100 uM)',...
                'Ivabradine (30 uM)',...
                'BaCl2 (5 mM)',...
                'CoCl2 (5 mM)',...
                'CdCl2 (5 mM)',...
                'NBQX (10uM)',...
                'L-AP4 (20uM)',...
                'GYKI53655 (100uM)',...
                'ACET (1 uM)' ,...
                'DAPV (50uM)',...
                'APB (10uM)',...
                'LY 341495 (10uM)',...
                'strychnine (0.5uM)',...
                'strychnine (25uM)',...
                'gabazine (10uM)',...
                'gabazine (25uM)',...
                'TPMPA (50uM)',...
                'TTX (100nM)',...
                'TTX (500nM)',...
                }));
        end
        
    end
    
end

