classdef ZFLarvalPrep < symphonyui.core.persistent.descriptions.SourceDescription
    
    methods
        
        function obj = ZFLarvalPrep()
            import symphonyui.core.*;
            
            obj.addProperty('time', datestr(now), ...
                'type', PropertyType('char', 'row', 'datestr'), ...
                'description', 'Time the tissue was mounted');
            obj.addProperty('mountedBy', '', ...
                'type', PropertyType('char', 'row', {'', 'Angueyra', 'Chen', 'Kunze', 'Zhao', 'Ball', 'Li', 'Ou', 'Qiao'}), ...
                'description', 'LiLab member who performed enucleation of tissue');
            obj.addProperty('mountingDate', datestr(now), ...
                'type', PropertyType('char', 'row', 'datestr'), ...
                'description', 'Time the tissue was dissected from subject');
            obj.addProperty('tissue', 'larva (whole)', ...
                'type', PropertyType('char', 'row', {'larva (whole)', 'eye (whole)', 'retina'}),...
                'description', 'experimental tissue');
            obj.addProperty('prep', 'larva', ...
                'type', PropertyType('char', 'row', {'larva', 'erg larvae', 'erg eye', 'whole mount cones', 'whole mount RGCs', 'slice', 'chop', 'dissociation', 'culture', ''}), ...
                'description', 'type of preparation');
            obj.addProperty('bathSolution', 'E3', ...
                'type', PropertyType('char', 'row', {'', 'E3', 'DMEM', 'Ringer', 'AmesBicarb', 'AmesHEPES', 'HibA'}), ...
                'description', 'The solution the tissue/larvae is bathed in during experiments');   
            obj.addProperty('storageSolution', 'E3', ...
                'type', PropertyType('char', 'row', {'', 'E3', 'DMEM', 'Ringer', 'AmesBicarb', 'AmesHEPES', 'HibA'}), ...
                'description', 'The solution the tissue/larvae is stored in');
            obj.addProperty('storageTemp', 'room temp', ...
                'type', PropertyType('char', 'row', {'', 'fridge', 'room temp', 'incubator', 'warm', 'body temp'}), ...
                'description', 'The temperature of the solution the tissue is stored in');
            obj.addProperty('eye', '', ...
    			'type', PropertyType('char', 'row', {'', 'left', 'right'}));
            obj.addProperty('recording mode', 'imaging', ...
    			'type', PropertyType('char', 'row', {'imaging', 'pierced cornea', 'on cornea', 'erg chamber', ''}));
            
            obj.addAllowableParentType('nih.squirrellab.shared.sources.zebrafish.Zebrafish');
        end
        
    end
    
end

